Hide self-PlayerBody when interacting with quickbelt
TommySoucy/H3MP pull request #221
Opened 2024-02-18 09:26 UTC by muskit

If the player is using a body avatar, their avatar will hide upon trying to look down and interact with their quickbelt. This allows them to more easily see their items without their avatar getting in the way.

I originally wanted to turn the avatar translucent, but the shaders used (Alloy) for the player bodies I've tested don't support transparency.

2024-02-18 17:42 UTC, TommySoucy requested changes

2024-02-18 17:42 UTC, TommySoucy commented on src/scripts/PlayerBody.cs
> +                // TODO: better way to determine if this is the local PlayerBody?
Body is ours if GameManager.currentPlayerBody == this

2024-02-18 17:42 UTC, TommySoucy commented on src/scripts/PlayerBody.cs
> +                    var usingQB = IsUsingQuickbelt();
Don't use var

2024-02-18 17:42 UTC, TommySoucy commented on src/scripts/PlayerBody.cs
> +            try
Don't expect an exception, check for nullity on hand instead

2024-02-18 17:42 UTC, TommySoucy commented on src/scripts/PlayerBody.cs
> +                            StartCoroutine(nameof(SelfUnhideCoroutine));
I'd prefer using AnvilManager.Run like vanilla, and to keep it consistent with how I've been running coroutines in the rest of the code

2024-02-19 16:56 UTC, TommySoucy commented
Cool, so I'll be testing and merging this by next update, might be a while.

2024-02-20 04:50 UTC, muskit commented
There's a suggestion in the H3 homebrew discord for configurable hide/unhide angles (they're currently consts). I was thinking of adding it with ConfigEntrys but I'm not sure how you're handling saved configuration.

2024-02-25 17:21 UTC, TommySoucy approved these changes

2024-02-25 17:21 UTC, merged

2024-02-25 17:21 UTC, TommySoucy commented
Thank you for your contribution